#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Motor,  mtr_S1_C1_1,     S1_C1_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     S1_C1_2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     S1_C2_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     S1_C2_2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     S1_C3_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     S1_C3_2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     S1_C4_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     S1_C4_2,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int currentTask,currentFunc;
int numFuncs[3];
int task1speed[20][8],task2speed[20][8],task3speed[20][8];
long duration[3],wait[3];

void horizLine(int x, int xTo, int y){
	int newX = x;
	int newXTo = xTo;
	int newY = y;
	if(x < 0)
		newX = 0;
	if(x > 99)
		newXTo = 99;
	if(xTo < 0)
		newX = 0;
	if(xTo > 99)
		newXTo = 99;
	if(y < 0)
		newY = 0;
	if(y > 63)
		newY = 63;
	nxtDrawLine(newX,newY,newXTo,newY);
}

void createRect(int xTL, int yTL,int xBR, int yBR){
	nxtDrawLine(xTL,yTL,xTL,yBR);
	nxtDrawLine(xBR,yTL,xBR,yBR);
	horizLine(xTL,xBR,yTL);
	horizLine(xTL,xBR,yBR);
}

task auto1;
task auto2;
task auto3;

task main()
{
}

task auto1{
	for(int func;func<numFuncs[0];func++){
		for(int speed;speed<8;speed++){
			if(task1speed[func][speed]){
				switch(speed){
					case 0:
						motor[S1_C1_1]=task1speed[func][speed];
						break;
					case 1:
						motor[S1_C1_2]=task1speed[func][speed];
						break;
					case 2:
						motor[S1_C2_1]=task1speed[func][speed];
						break;
					case 3:
						motor[S1_C2_2]=task1speed[func][speed];
						break;
					case 4:
						motor[S1_C3_1]=task1speed[func][speed];
						break;
					case 5:
						motor[S1_C3_2]=task1speed[func][speed];
						break;
					case 6:
						motor[S1_C4_1]=task1speed[func][speed];
						break;
					case 7:
						motor[S1_C4_2]=task1speed[func][speed];
						break;
				}
			}
			wait1Msec(duration[0]);
			if(task1speed[func][speed]){
				switch(speed){
					case 0:
						motor[S1_C1_1]=0;
						break;
					case 1:
						motor[S1_C1_2]=0;
						break;
					case 2:
						motor[S1_C2_1]=0;
						break;
					case 3:
						motor[S1_C2_2]=0;
						break;
					case 4:
						motor[S1_C3_1]=0;
						break;
					case 5:
						motor[S1_C3_2]=0;
						break;
					case 6:
						motor[S1_C4_1]=0;
						break;
					case 7:
						motor[S1_C4_2]=0;
						break;
				}
			}
			wait1Msec(wait[0]);
		}
	}
}

task auto2{
	for(int func;func<numFuncs[1];func++){
		for(int speed;speed<8;speed++){
			if(task2speed[func][speed]){
				switch(speed){
					case 0:
						motor[S1_C1_1]=task2speed[func][speed];
						break;
					case 1:
						motor[S1_C1_2]=task2speed[func][speed];
						break;
					case 2:
						motor[S1_C2_1]=task2speed[func][speed];
						break;
					case 3:
						motor[S1_C2_2]=task2speed[func][speed];
						break;
					case 4:
						motor[S1_C3_1]=task2speed[func][speed];
						break;
					case 5:
						motor[S1_C3_2]=task2speed[func][speed];
						break;
					case 6:
						motor[S1_C4_1]=task2speed[func][speed];
						break;
					case 7:
						motor[S1_C4_2]=task2speed[func][speed];
						break;
				}
			}
			wait1Msec(duration[1]);
			if(task2speed[func][speed]){
				switch(speed){
					case 0:
						motor[S1_C1_1]=0;
						break;
					case 1:
						motor[S1_C1_2]=0;
						break;
					case 2:
						motor[S1_C2_1]=0;
						break;
					case 3:
						motor[S1_C2_2]=0;
						break;
					case 4:
						motor[S1_C3_1]=0;
						break;
					case 5:
						motor[S1_C3_2]=0;
						break;
					case 6:
						motor[S1_C4_1]=0;
						break;
					case 7:
						motor[S1_C4_2]=0;
						break;
				}
			}
			wait1Msec(wait[1]);
		}
	}
}

task auto3{
	for(int func;func<numFuncs[2];func++){
		for(int speed;speed<8;speed++){
			if(task3speed[func][speed]){
				switch(speed){
					case 0:
						motor[S1_C1_1]=task3speed[func][speed];
						break;
					case 1:
						motor[S1_C1_2]=task3speed[func][speed];
						break;
					case 2:
						motor[S1_C2_1]=task3speed[func][speed];
						break;
					case 3:
						motor[S1_C2_2]=task3speed[func][speed];
						break;
					case 4:
						motor[S1_C3_1]=task3speed[func][speed];
						break;
					case 5:
						motor[S1_C3_2]=task3speed[func][speed];
						break;
					case 6:
						motor[S1_C4_1]=task3speed[func][speed];
						break;
					case 7:
						motor[S1_C4_2]=task3speed[func][speed];
						break;
				}
			}
			wait1Msec(duration[2]);
			if(task3speed[func][speed]){
				switch(speed){
					case 0:
						motor[S1_C1_1]=0;
						break;
					case 1:
						motor[S1_C1_2]=0;
						break;
					case 2:
						motor[S1_C2_1]=0;
						break;
					case 3:
						motor[S1_C2_2]=0;
						break;
					case 4:
						motor[S1_C3_1]=0;
						break;
					case 5:
						motor[S1_C3_2]=0;
						break;
					case 6:
						motor[S1_C4_1]=0;
						break;
					case 7:
						motor[S1_C4_2]=0;
						break;
				}
			}
			wait1Msec(wait[2]);
		}
	}
}
