#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
===Dual Motor Tester===

Made by Shupe
Edited by Ben and David

===Instructions===

Press and release orange button to change motors.
Press and hold orange button to run selected motor(s).
Use arrows to change the speed of the selected motor(s).
*/

int speed[] = {100, 100, 100};
int currentMotor = 1; //3 = both

task main()
{
	while(true){
		if(nNxtButtonPressed == 3){
			clearTimer(T1);
			while(time1(T1) <= 500 && nNxtButtonPressed != -1){}
			if(time1(T1) <= 500){
				if(++currentMotor > 3){
					currentMotor = 1;
				}
			}else{
				switch(currentMotor){
				case 1:
					motor[leftDrive] = speed[currentMotor-1];
					break;
				case 2:
					motor[rightDrive] = speed[currentMotor-1];
					break;
				case 3:
					motor[leftDrive] = speed[currentMotor-1];
					motor[rightDrive] = speed[currentMotor-1];
					break;
				}
			}
		}else{
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
		}
		if(nNxtButtonPressed == 1){
			speed[currentMotor-1] += 5;
			if(speed[currentMotor-1] > 100){
				speed[currentMotor-1] = 100;
			}
			wait1Msec(200);
		}
		if(nNxtButtonPressed == 2){
			speed[currentMotor-1] -= 5;
			if(speed[currentMotor-1] < -100){
				speed[currentMotor-1] = -100;
			}
			wait1Msec(200);
		}
		if(currentMotor == 3){
			nxtDisplayTextLine(3, "Both Motors: %d", speed[currentMotor-1]);
		}else{
			nxtDisplayTextLine(3, "Motor %d: %d", currentMotor, speed[currentMotor-1]);
		}
	}
}
