#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     tMux,           sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     leftWheel,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    dragger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    scorer,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//	Motors are reversed so that the back is considered the front for easier programming	//

#include "JoystickDriver.c"
#include "Assets\Headers\Autonomous_Funcs.h"
#include "Assets\Headers\h359_14-15.h"

long waitDuration;
bool ramp = true;
bool kickstand = true;
bool centerScore = true;

int irPos;
int centerRotation; //1 = kickstand facing alliance PZ, 2 = 45, 3 = 90

task main()
{
	configLine("Select Options: ");
	configLine("Wait: ", &waitDuration, "ms", 0, 50, 5000);
	configLine("", &ramp, "", "Ramp", "Parking Zone");
	//configLine("KS: ", &kickstand, "", "Yes", "No");
	configLine("Score in: ", &centerScore, "", "CG", "RG");
	startDisplay(true, true);
	initializeRobot();
	//waitForStart();
	//stopTask(readMsgFromPC);
	wait1Msec(waitDuration);
	if(ramp){
		move(30, 2000, bwd); //drive off ramp
		move(60, 500, bwd); //drive towards goals
		if(centerScore){
			//drag 60cm
			servo[dragger] = DRAGGER_DOWN;
			if(kickstand){
				//knock down kickstand
			}else{
			}
			//score in center goal and 60cm goal
			//drag back the goal
		}else{
			//score in and drag 30cm
			if(kickstand){
				//knock down kickstand
			}else{
			}
			//score in 90cm goal, drag back
		}
	}else{																				//Start in parking zone
		//drive off ramp
		//drive towards goals
		if(centerScore){
			//drag 60cm
		}else{
			//score in and drag 30cm
		}
		if(kickstand){
			//knock down kickstand
		}
		if(centerScore){
			//score in center goal and 60cm goal
			//drag back the goal
		}else{
			//score in 90cm goal, drag back
		}
	}
}
