#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     tMux,           sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     leftWheel,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    dragger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Assets\Special Joystick Functions.h"

int threshold = 10;
int maxDrive = 100;
int leftOffset, rightOffset = 12;

bool ignoreJ1B5;
bool ignoreJ1B6;

bool tMuxValue(tSensors sensor,int index){
	int mask = pow(2,index-1);
	if(SensorValue[sensor]&mask){
		return true;
	}
	return false;
}

task main()
{
	servoChangeRate[dragger] = 0;
	waitForStart();
	while(true){
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) >= threshold)
			motor[leftWheel] = joystickExponential(threshold, maxDrive-rightOffset, joystick.joy1_y1);
		else motor[leftWheel] = 0;
		if(abs(joystick.joy1_y2) >= threshold)
			motor[rightWheel] = joystickExponential(threshold, maxDrive-leftOffset, joystick.joy1_y2);
		else motor[rightWheel] = 0;
		if(abs(joystick.joy2_y1) >= threshold)
			motor[intake] = joystickExponential(threshold, 100, joystick.joy2_y1);
		else motor[intake] = 0;
		if(abs(joystick.joy2_y2) >= threshold){
			motor[lift] = joystickExponential(threshold,100,joystick.joy2_y2);
		}else{
			motor[lift] = 0;
		}
		if(joy1Btn(5) && !ignoreJ1B5)
			ignoreJ1B5 = true;
		else if(!joy1Btn(5)&& ignoreJ1B5){
			servo[dragger] = 110;
			ignoreJ1B5 = false;
		}
		if(joy1Btn(6) && !ignoreJ1B6)
			ignoreJ1B6 = true;
		else if(!joy1Btn(6)&& ignoreJ1B6){
			servo[dragger] = 10;
			ignoreJ1B6 = false;
		}
	}
}
