#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     tMux,           sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    dragger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Assets\Headers\Teleop_Funcs.h"
#include "Assets\Headers\h359_14-15.h"

int threshold = 10;
int maxDrive = 100;
int leftOffset, rightOffset = 12;

bool ignoreJ1B5;
bool ignoreJ1B6;

bool tMuxValue(tSensors sensor,int index){
	int mask = pow(2,index-1);
	if(SensorValue[sensor]&mask){
		return true;
	}
	return false;
}

task main()
{
	servoChangeRate[dragger] = 0;
	waitForStart();
	while(true){
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) >= threshold)
			motor[leftWheel] = joystickExponential(threshold, maxDrive-rightOffset, joystick.joy1_y1);
		else motor[leftWheel] = 0;
		if(abs(joystick.joy1_y2) >= threshold)
			motor[rightWheel] = joystickExponential(threshold, maxDrive-leftOffset, joystick.joy1_y2);
		else motor[rightWheel] = 0;
		if(abs(joystick.joy2_y1) >= threshold)
			motor[intake] = joystickExponential(threshold, 100, joystick.joy2_y1);
		else motor[intake] = 0;
		if(abs(joystick.joy2_y2) >= threshold){
			motor[lift] = joystickExponential(threshold,100,joystick.joy2_y2);
		}else{
			motor[lift] = 0;
		}
	if(toggleJ1B(5))
			servo[dragger] = DRAGGER_UP;
	if(toggleJ1B(6))
			servo[dragger] = DRAGGER_DOWN;
	}
}
