#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     tMux,           sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     tube,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftWheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     bucketLift,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    heartbeat,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int threshold = 10;
int maxDrive = 100;

int joystickExponential(int deadzone, int maxSpeed, int joystickCurrent){
	if(joystickCurrent == 0){
		return 0;
	}
	int polarity = joystickCurrent/abs(joystickCurrent);
	long maxSpeed2 = maxSpeed*maxSpeed;
	long newInside = maxSpeed-sqrt(((abs(joystickCurrent)-127)*maxSpeed2)/(deadzone-127));
	return polarity*newInside;
}

int joystickLinear(int deadzone, int maxSpeed, int joystickCurrent){
	if(joystickCurrent == 0){
		return 0;
	}
	int polarity = joystickCurrent/abs(joystickCurrent);
	long newInside = maxSpeed*((abs(joystickCurrent)-127)*maxSpeed)/(deadzone-127);
	return polarity*newInside;
}

bool tMuxValue(tSensors sensor,int index){
	int mask = pow(2,index-1);
	if(SensorValue[sensor]&mask){
		return true;
	}
	return false;
}

task servoHeartbeat{
	while(true){
		servo[heartbeat] = 0;
		while(ServoValue[heartbeat] != 0){}
		servo[heartbeat] = 50;
		while(ServoValue[heartbeat] != 50){}
	}
}

task main()
{
	startTask(servoHeartbeat);
	waitForStart();
	while(true){
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) >= threshold)
		{
			motor[leftWheel] = joystickExponential(threshold, maxDrive, joystick.joy1_y1);
			}else{
			motor[leftWheel] = 0;
		}
		if(abs(joystick.joy1_y2) >= threshold){
			motor[rightWheel] = joystickExponential(threshold, maxDrive, joystick.joy1_y2);
			}else{
			motor[rightWheel] = 0;
		}
		if(abs(joystick.joy2_y1) >= threshold){
			motor[bucketLift] = joystickLinear(threshold, 90, joystick.joy2_y1);
		}else{
			motor[bucketLift] = 0;
		}
		if((joystick.joy2_y2 >= threshold) || (joystick.joy2_y2 <= threshold && !tMuxValue(tMux,2) && !tMuxValue(tMux,3))){
				motor[lift] = joystickLinear(threshold, 80, joystick.joy2_y2);
		}else{
			motor[lift] = 0;
		}
		if(joy2Btn(7) == 1){
			motor[intake] = 80;
		}else if(joy2Btn(8) == 1){
			motor[intake] = -80;
		}else{
			motor[intake] = 0;
		}
		if(joy2Btn(5) == 1){
			motor[tube] = 50;
		}else if(joy2Btn(6) == 1){
			motor[tube] = -50;
		}else{
			motor[tube] = 0;
		}
	}
}
