#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Motor,  mtr_S1_C1_1,     S1_C1_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     S1_C1_2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     S1_C2_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     S1_C2_2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     S1_C3_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     S1_C3_2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     S1_C4_1,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     S1_C4_2,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
===Dual Motor Tester===

Made by Shupe
Edited by Ben and David

===Instructions===
	Controller Selection
Use the arrows to change the motor controller.
Press and release the orange button to select that controller.
	Motor Running
Press and release the orange button to change motors.
Press and hold the orange button to run selected motor(s).
Use the arrows to change the speed of the selected motor(s).
*/

int speed[] = {100, 100, 100};
int currentMotor = 1; //3 = both
int motorController = 1;

void motor1(int speed){
	switch(motorController){
		case 1:
			motor[S1_C1_1] = speed;
			break;
		case 2:
			motor[S1_C2_1] = speed;
			break;
		case 3:
			motor[S1_C3_1] = speed;
			break;
		case 4:
			motor[S1_C4_1] = speed;
			break;
	}
}

void motor2(int speed){
	switch(motorController){
		case 1:
			motor[S1_C1_2] = speed;
			break;
		case 2:
			motor[S1_C2_2] = speed;
			break;
		case 3:
			motor[S1_C3_2] = speed;
			break;
		case 4:
			motor[S1_C4_2] = speed;
			break;
	}
}

task controllerFlash{
	while(true){
		clearTimer(T1);
		while(time1(T1) <= 500){
			nxtDisplayTextLine(1,"Controller: [%d]",motorController);
		}
		nxtDisplayTextLine(1,"Controller:");
		wait1Msec(500);
	}
}

task main()
{
	//Motor Controler Selection
	startTask(controllerFlash);
	while(true){
		if(nNxtButtonPressed == 1){
			while(nNxtButtonPressed != -1){}
			if(++motorController > 4){
				motorController = 4;
			}
		}
		if(nNxtButtonPressed == 2){
			while(nNxtButtonPressed != -1){}
			if(--motorController < 1){
				motorController = 1;
			}
		}
		if(nNxtButtonPressed == 3){
			while(nNxtButtonPressed != -1){}
			break;
		}
	}
	stopTask(controllerFlash);
	nxtDisplayClearTextLine(1);
	nxtDisplayCenteredTextLine(1,"Controller: %d",motorController);
	while(true){
		if(nNxtButtonPressed == 3){
			clearTimer(T1);
			while(time1(T1) <= 500 && nNxtButtonPressed != -1){}
			if(time1(T1) <= 500){
				if(++currentMotor > 3){
					currentMotor = 1;
				}
			}else{
				switch(currentMotor){
				case 1:
					motor1(speed[currentMotor-1]);
					break;
				case 2:
					motor2(speed[currentMotor-1]);
					break;
				case 3:
					motor1(speed[currentMotor-1]);
					motor2(-speed[currentMotor-1]);
					break;
				}
				while(nNxtButtonPressed != -1){/*Do nothing*/}
				motor1(0);
				motor2(0);
			}
		}
		if(nNxtButtonPressed == 1){
			speed[currentMotor-1] += 5;
			if(speed[currentMotor-1] > 100){
				speed[currentMotor-1] = 100;
			}
			wait1Msec(200);
		}
		if(nNxtButtonPressed == 2){
			speed[currentMotor-1] -= 5;
			if(speed[currentMotor-1] < -100){
				speed[currentMotor-1] = -100;
			}
			wait1Msec(200);
		}
		if(currentMotor == 3){
			nxtDisplayTextLine(3, "Both Motors: %d", speed[currentMotor-1]);
		}else{
			nxtDisplayTextLine(3, "Motor %d: %d", currentMotor, speed[currentMotor-1]);
		}
	}
}
